### PR TITLE
Bump to 0.3.0 & rename app-id to org.tabos.twofun

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
cc @janbrummer as you can see, the new app-id is not set correctly.

**Comment by bilelmoussaoui** [comment]
The id https://gitlab.com/tabos/twofun/blob/master/data/org.tabos.twofun.appdata.xml.in#L7 here is wrong. You should remove the .desktop suffix and add a launchable tag to the metainfo file.

Once it's done, you can bump the version here & merge it and it should be ready to go.

**Comment by janbrummer** [comment]
So i need to bump a new version with the above changes, ok. And then adjust the flatpak json here for the new version, understood. But where is the naming change actually happening? What's the architecture for this move? Is there a documentation?

**Comment by bilelmoussaoui** [comment]
There's nothing documented for now and will probably never be. We don't want to make app-id renaming an easy thing. You just ping a reviewer/maintainer and we will take care of that.

**Pull request closed without merging**
